# Generated by Django 4.2.13 on 2024-05-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_subcategory_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
