# Generated by Django 4.2.13 on 2024-05-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistproducts',
            options={'verbose_name': 'Wishlist Product', 'verbose_name_plural': 'Wishlist Products'},
        ),
    ]
