# Generated by Django 4.2.13 on 2024-05-30 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0002_receipt_receiptproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='staff',
            field=models.ManyToManyField(related_name='staffWarehouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
