# Generated by Django 4.2.13 on 2024-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_receiptproduct_warehouse_alter_warehouse_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
