# Generated by Django 4.2.13 on 2024-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_receipt_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
