# Generated by Django 4.2.13 on 2024-06-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_receipt_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='costPrice',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=50),
        ),
    ]
